### ISSUE TITLE
Audio Equalizer

### ISSUE THREAD

**Issue by keshavbhatt** [keshavbhatt/olivia#20]

**Comment by keshavbhatt** [comment]
fixed with commit https://github.com/keshavbhatt/olivia/commit/48b0ff889e96fcfd240ea18e235bddaba2656391

**Comment by joemarangi** [comment]
#response_container_BBPPID{font-family: Calibri, sans-serif; font-size:12pt; color: #1F497D;}  Hi Can I please ask your help? I haven't a clue how I ended up on this group but how can I leave ? I have nothing to do with this program or GitHub . Can you help direct me ?                                                                                                                                                                        Joe Marangi                                                                                                                                                                           From: notifications@github.comSent: July 11, 2019 1:14 p.m.To: olivia@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [keshavbhatt/olivia] Audio Equalizer (#20)  fixed with commit 48b0ff8
