### ISSUE TITLE
No streaming audio through any source.

### ISSUE THREAD

**Issue by zds388** [keshavbhatt/olivia#81]
I can provide any kind of log you need. New to this and not exactly sure what to include.

**Comment by zds388** [comment]
olivia --debug
Store not Open , opening...
Store open for queries "/home/zack/.local/share/org.keshavnrj.ubuntu/Olivia/storeDatabase/hjkfdsll/hjkfdsll.db"

**Comment by keshavbhatt** [comment]
if you did not installed it via snap store, then please provide the version of mpv you are using. make sure it is newer than the version described in readme file.

**Comment by EdisAganovic** [comment]
```
sudo pamac install downgrade
downgrade mpv
```
* Select version 0.31    2
Issue is with version 0.32

**After that Olivia works.**

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.1.5

**Comment by keshavbhatt** [comment]
thanks, this is helpful for user who installed olivia from source and with other type of installs via package managers. 
issue is not present if user installs olivia using snap.

**Comment by zds388** [comment]
Fix worked as described. Thanks for the fast response!

**Comment by benchile55** [comment]
Hey there,
Thanks for this awesome media player..  your eq-  and youtube integrations are my favs.
I am a manjaro user and snap Olivia is not working with the latest MPV release yet.. the only way to have audio coding is as EdisAganovic recommended 18 days ago.. and mpv has been updated twice since then... Is there any choice that you can solve this issue with the latest MPV version please ?  

Cheers

**Comment by keshavbhatt** [comment]
i will look what changes they made to later version and make changes in their new accords.
