### ISSUE TITLE
Add option to disable analytics and prevent analytics.php from filling up home folder, and stop collecting IP addresses of Olivia users

### ISSUE THREAD

**Issue by pizzadude** [keshavbhatt/olivia#82]
Can you add an option to disable analytics? Also, maybe implement it better, so that "analytics.php" and "analytics.php.1" and so on doesn't fill up my home folder?

**Comment by pizzadude** [comment]
Oh and FYI http://ktechpit.com/USS/Olivia/services/ is public with every IP address of every Olivia user. :)

**Comment by keshavbhatt** [comment]
smart, since you know everything what possibly can someone do with that data ?? xan tou find my IP and identify me personally there ?? i know that and you are welcome to add an option to disable it. thanks my exams going on. i will do it after 7   feb myself. update olivia that analytic.php problem is gone already.

**Comment by pizzadude** [comment]
I'm not saying anyone can do anything with the data. I'm not bashing Olivia either, it's a nice app. I just think it's not smart to have that data public, also is collecting the IP address really necessary either?

**Comment by keshavbhatt** [comment]
its not and this data is private now. analytic is planned to have a full rewrite in future. i appreciate your investigation though thanks.
